go-between/musicbox

- README.md
I ran into a problem with npm 6.13.4 where `npm tsc` would not run. After doing `npm install -g typescript` (which may or may not have been needed), I was able to just run `tsc` from the command line.
> Update some instructions for running typescript compilation

- netlify.toml
Netlify supports some `toml` file where we can add a redirect to send everything back to `index.html`, which is a thing we need to do to support direct linking to, like `/login` or `/room/whatever`.
> Add netlify config with spa redirect

- src/Player/Player.tsx
- src/Player/PlayerPrimitive.tsx
- src/lib/WebsocketClient/client.ts
- src/rebass__forms.extension.d.ts
Extracts the `ReactPlayer` and surrounding code into a `PlayerPrimitive` component.  Adds a volume slider and a progress bar, disables controls and click-to-pause on youtube videos.
Solves at least the "start halfway through" bug (by default if you call `seekTo` with a decimal, it will treat it as a percent of the video that you want to seek to, so when a song starts and we find that the diff is like 0.68 seconds, it'd jump to 68% of the way through).
Maybe also solved the "song doesn't start"?  We'll have to see.
> Why dont you just go ahead and play

- src/Home/Home.tsx
- src/Login.tsx
- src/Player/Player.tsx
- src/Room/MessageEntry.tsx
- src/Room/Messages.tsx
- src/components/Footer.tsx
- src/theme.ts
- uses setTimeout hack to make sure new chat messages scroll to the most recent. This happens because there is a small async delay while react renders the message list while we're trying to reset the scrollTop position.
- WIP design stuffs
Basecamp Todo: https://3.basecamp.com/4361952/buckets/14871813/todos/2412439281/edit?replace=true
> Ensure new chat messages scroll to bottom

- src/Room/Messages.tsx
Reading names is difficult when there's no way to differentiate between them in chat.
This adds a color encoding scheme so each user's color will show up unique based on the user name.
Not perfect, but a start.
> Unique name colors

- src/App.tsx
- src/Player/Player.tsx
- src/Room/Messages.tsx
- src/Room/Room.tsx
- src/Room/Users.tsx
- src/RoomPlaylist/RoomPlaylist.tsx
- src/lib/WebsocketClient/client.ts
Updates websocket client to subscribe to all room-related channels after activating a room, rather than upon the various child components mounting and calling `subscribeTo` whatever.  We should see the room itself rerender less-often than the child components, so I'm hoping this will address some instability in how the websocket connection is handled.
> Websocketeer

- src/Room/Main.tsx
With the context reorganizing we lost our ability to set current record when the page loads, meaning you'd see no song if there's one in progress when you refresh (or join a room new).  This fixes that for now.
> Hacky hack ensure that current record is set when page loads fresh

- src/Room/MessageEntry.tsx
My sister's in town, so I'm very distracted tonight, but I wanted to make sure I did at least ONE thing tonight, so I updated the message input to be a textarea that gives the user some more breathing room when typing longer messages.
> Replace chat message input with textarea

- src/Context/UserContextProvider.tsx
- src/Home/RoomSelector.tsx
- src/Invitation/Invitation.tsx
- src/Invitations/Invitations.tsx
- src/Room/Messages.tsx
- src/RoomPlaylist/RoomPlaylist.tsx
- src/UserPlaylist/UserPlaylist.tsx
Set our fetch policy to always use the network instead of relying on the cache -- ensures we don't run into weird caching bugs when you switch rooms!
> Always refetch data with graphql to avoid weird caching issues

- src/QuickAdd/QuickAdd.tsx
Removes a reference to `query` that we accidentally left in when refactoring search (in favor of `debouncedQuery`) which was causing us to fire youtube searches on every keypress instead of debouncing 500ms.  Also updates the results container to first check for errors before rendering nothing or results as appropriate.
> Remove query in favor of debounced query, allow errors to display

- package-lock.json
- package.json
- src/Player/Player.tsx
- src/Player/PlayerPrimitive.tsx
- src/Player/VolumeContextProvider.tsx
- src/Player/index.ts
- src/QuickAdd/Results.tsx
- src/QuickAdd/ResultsContextProvider.tsx
- src/QuickAdd/Search.tsx
- src/QuickAdd/graphql.ts
- src/QuickAdd/types.ts
- src/QuickAdd/youtube.ts
- src/Room/Room.tsx
If you could hear the below gif, you would hear the main player muted (if anything is playing) anytime a preview begins.  You would also hear the preview player playing at the same volume that the main player was playing at before the preview started.
Improvements:
1. Styling
2. Volume controls on preview player?
3. Better usage of context providers (full discloser, this was my first use of a context provider in React.  I was aware of the tech but just never used it 🤷‍♂ )
> add ability to preview songs in My Library and Youtube searches

- src/Player/Player.tsx
- src/QuickAdd/ResultsContextProvider.tsx
- src/Room/Chat.tsx
- src/Room/Message.tsx
- src/Room/MessageEntry.tsx
- src/Room/Messages.tsx
- src/theme.ts
Taking some heavy inspiration from slack here:
- updates style of "song banner" in the chat
- makes starred messages more noticeable 
- only shows the ability to star a message on hover
- adds hover styles
- tightens up spacing to make text more readable
> Chat cleanup

- src/components/SideNav.tsx
Despite the branch name this does not actually remove routes, but rather just removes the links from the sidebar navigation thing.  We're not blocking anyone from accessing `signup` or `invitations` but rather discouraging the casual browsing to those things.
> Remove links to signup/invitations

- src/Room/Main.tsx
- src/RoomHistory/RoomHistory.tsx
- src/RoomHistory/graphql.ts
- src/RoomPlaylist/RoomPlaylist.tsx
Does a bit of cleanup around selecting the `Main` component in the room.  Also fixes the mysterious room history bug by never caching the results.  Which we may consider doing for all of our queries since we're not actually using the cache at all currently.
> Fixing uh things

- src/Library/Songs/Results.tsx
- src/Library/Songs/index.tsx
Some "light reading" leads me to believe that overflow doesn't seem to like it when it can find find a relative parent position.
> [bugfix] Library scrolling bug

- src/Library/SongDetails/SongDetails.tsx
- src/Library/SongDetails/graphql.ts
- src/Library/Songs/Results.tsx
- src/Library/TagsContextProvider.tsx
- src/Library/graphql.ts
- src/QuickAdd/Search.tsx
- src/QuickAdd/graphql.ts
No UI changes, just fixing up the react app to request `libraryRecords` instead of `songs`.  Corresponds to [this api pr](https://github.com/go-between/musicbox-api/pull/109).
> Use library records duh

- src/Library/SongDetails/SongDetails.tsx
- src/Player/Player.tsx
- src/Player/PlayerContextProvider.tsx
- src/Player/PlayerPrimitive.tsx
- src/Player/Progress.tsx
- src/QuickAdd/Results.tsx
- src/Room/Main.tsx
pair: @DLavin23 
Some Quality of Life fixes:
- Allows the main react player to always be rendered on the page and to find its home on the main room page via positioning instead of react portals (removes issue where the player rerenders and restarts when you navigate between room - library - recommendations)
- Removes `onProgress` from the react player itself, instead allowing the `Progress` component to calculate its own offsets based on when the song started playing.  Removes issue where React was re-rendering the whole player every half second
- Adds a youtube icon on the bottom bar with a link to the original song
- Allows user controls on the song details view so you can skip around the video, although it will still play "on top" of any song playing currently in the …
> So seeeeeeeemless

- src/Player/PlayerPrimitive.tsx
@trumanshuck 
auto height is bad here because it covers up the other buttons in the room
> quickfix to make height fixed

- src/Player/PlayerPrimitive.tsx
- src/Room/Main.tsx
- src/components/Table.tsx
Attempts to fix that weird library scrolling bug (https://github.com/go-between/musicbox/pull/83), yet again. I think it came back because position relative was applied to a `ul` element and we moved to a `table` element.
Also, our work from last night produced a new bug when you navigate to the library during a song. Look at all that extra space! 
This is because the container for our video has a fixed height of 350px, so even though it's "hidden" we still run into issues with the height. I used `overflow: hidden` to solve it for now.
> [bugfix] library bugs

- src/UserPlaylist/UserPlaylist.tsx
Adds a big gross "remove all" button to the bottom of a user's playlist just in case they enqueue their whole library.
This marks the last new feature before we begin "operation where did all of this gross ux come from, anyway?!"
> Add button to clear playlist
