.env.template, .eslintrc.js, .gitignore, .prettierrc.js, package-lock.json, package.json, src/App.tsx, src/Login.tsx, src/Router.tsx, src/index.tsx, webpack.config.js
Adds dotenv, react-router-dom.  Adds first router with redirect to login, allows folks to execute a login and be redirected home.
=> First routes

src/Home.tsx, src/Room.tsx, src/Router.tsx, src/components/RoomSelector.tsx, src/components/TeamSelector.tsx
Allows someone to select and join a room.
=> Allow someone to join a room

src/Home/Home.tsx, src/Home/RoomSelector.tsx, src/Home/TeamSelector.tsx, src/Home/graphql.ts, src/Room/Room.tsx, src/RoomPlaylist/RoomPlaylist.tsx, src/RoomPlaylist/graphql.ts, src/RoomPlaylist/index.ts, src/lib/WebsocketClient/client.ts, src/lib/WebsocketClient/types.ts, src/lib/apiTypes.ts
Adds ability to view all songs enqueued in room.  Also cleans up some conflicting types used by the `Home` component by extracting their types to a `graphql.ts` file.
=> Room queue

src/Home/Home.tsx, src/Home/RoomSelector.tsx, src/Home/TeamSelector.tsx, src/components/Container.tsx, src/theme.ts
@tshuck 
Made time to chip away and try to make some small improvements. Planning to do a lot of styling using this rebass SX prop because I can test stuff super fast. Eventually it might be wise to create some cleaner components.
=> Design Updates to the home page

src/Invitation/Invitation.tsx, src/Invitation/graphql.ts, src/Invitation/index.ts, src/Invitations/Invitations.tsx, src/Invitations/graphql.ts, src/Invitations/index.ts, src/Router.tsx
Allows people to retrieve existing invitations and resend them, to create new invitations, and for folks to accept invitations.  Real nice.
=> Whole world invitational

src/App.tsx, src/Home/RoomSelector.tsx, src/Invitations/Invitations.tsx, src/Room/Messages.tsx, src/theme.ts
In the words of [Dory](https://www.youtube.com/watch?v=0Hkn-LSh7es), "just keep swimming." Since I didn't get a chance to contribute yesterday, I felt the need to at least do SOMETHING, so I made the some inputs more noticeable. Also, the chat history jumps to the bottom when the page loads now too.
=> Just some tiny little improvements

src/Room/Messages.tsx
=> add space before "during"

src/Player/Player.tsx, src/Room/Messages.tsx, src/Room/Room.tsx
Trying out a new layout until I get some time to properly think through the design and UX of this app. Also, I added a fix for the bug Sean pointed out, when you paste links or image files in chat and it breaks the overflow. Lastly, I used @Shiggiddie's random color generator thing to apply it to the default chat user image placeholder instead of the text
=> Design/Layout Updates

src/Player/Player.tsx, src/QuickAdd/QuickAdd.tsx, src/QuickAdd/YoutubeSearch.tsx, src/Room/Room.tsx, src/lib/setters.ts
Updates the search to move it to the center and allows library/youtube search to be a modal sort of experience.  Also adds the name of the current playing song, and swaps room/my library info from left-to-rightsies.
@DLavin23 especially I could use some of your help cleaning this up!
=> Quality of life

src/Player/Player.tsx, src/Player/PlayerPrimitive.tsx, src/Room/Chat.tsx, src/Room/Main.tsx, src/Room/Room.tsx, src/Room/graphql.ts, src/RoomPlaylist/RoomPlaylist.tsx, src/components/SideNav.tsx, src/components/index.ts, src/lib/WebsocketClient/types.ts
Another shiftaround of the room layout.  Introduces side navigation, pulls user/room playlist behind "tabs", moves chat back to the right.
=> Shift chat back to right and hide playlists behind buttons

src/Home/Home.tsx, src/Player/Player.tsx, src/QuickAdd/QuickAdd.tsx, src/Room/Main.tsx, src/components/Header.tsx, src/components/SideNav.tsx, src/theme.ts
- fixes the overflow scroll issue from earlier
- makes the tabs just a tiny bit better, they still stink
- some other small, tiny stuff.
=> design tweaks for jam city friday

src/Player/PlayerPrimitive.tsx, src/Room/Main.tsx
original https://github.com/go-between/musicbox/pull/40 didn't quite solve scrolling the main content area for my small little macbook. Still work to do here, but this should get us through today.
=> actually fix the scroll issue for today

src/Room/Messages.tsx, src/Room/graphql.ts, src/lib/WebsocketClient/types.ts
Expects to receive song directly from message instead of via room playlist record.
=> Fetch song name directly from message

package-lock.json, package.json, src/Room/PlaylistRecordContextProvider.tsx, src/UserPlaylist/UserPlaylist.tsx, src/UserPlaylist/UserPlaylistRecord.tsx
Adds `react-beautiful-dnd` to allow folks to reorder the songs that they have enqueued.
=> The great reordering

src/QuickAdd/YoutubeSearch.tsx
Adds an error message to youtube search when we don't get a successful response.
=> Display an error message when youtube is broke

CONTRIBUTING.md, LICENSE.txt, README.md
Alright, adds a [source available](https://en.wikipedia.org/wiki/Source-available_software) license from [https://commonsclause.com/](https://commonsclause.com/).  Adds a CONTRIBUTING.md doc.
=> Add contributing, license thing, updates to readme

package-lock.json, package.json
Bumped webpack to a slightly newer version and ran `npm audit fix` to close whatever security vulnerabilities we've got (452 low, 1 moderate).
=> Upgrade webpack to minor verison, run npm audit fix

package-lock.json
One more vulnerability popped up after we resolved the last ones.
=> Update minimist version to skip another vulnerability

src/Player/Player.tsx, src/Player/PlayerPrimitive.tsx, src/QuickAdd/Results.tsx, src/Room/Chat.tsx, src/Room/Main.tsx, src/Room/Message.tsx, src/Room/MessageEntry.tsx, src/Room/Users.tsx, src/theme.ts
Working on some new thoughts for the chat messages.
- uses a "star" icon to pin messages
- moves the "commented during song" below the original message
- adds a nicer empty state while now videos are playing
- moves the activate user list to a horizontal list
=> [WIP] design updates

src/Context/AuthContextProvider.tsx, src/Invitation/Invitation.tsx, src/Login.tsx, src/Player/Player.tsx, src/Room/Message.tsx, src/Room/MessageEntry.tsx, src/Signup/Signup.tsx, src/lib/localStore.ts
A couple of small fixes:
- Allows newlines in chat to be presented, and newlines to be entered with shift+enter as you'd expect
- Moves all of our `localStorage` into `lib/localStore`
- Allows volume choice to be persisted
- Adds a show/hide video button and allows that choice to be persisted
=> Hide that bideo

src/QuickAdd/QuickAdd.tsx, src/QuickAdd/Results.tsx, src/QuickAdd/ResultsContextProvider.tsx, src/QuickAdd/Search.tsx
Extracts search results and selection into a context helper.  Extracts search itself into a separate component.  Adds a SECRET FEATURE SEE IF YOU CAN GUESS!!!!!!
=> Result select so fancy

src/Room/Message.tsx
fixes an annoying (for me) alignment issue when messages by other people weren't starred and don't have the padding of a star in their message.
=> Alignment fix

src/Room/Message.tsx
=> starred message fix

src/Player/Player.tsx, src/Room/Message.tsx, src/Room/MessageEntry.tsx, src/theme.ts
- updates the room player design
- starting to re-enforce some icons
- simplifies the chat textbox even more
=> More design improvements

src/Player/Player.tsx, src/Room/Approval.tsx, src/Room/Chat.tsx, src/Room/Main.tsx, src/Room/Room.tsx, src/Room/Users.tsx, src/Room/graphql.ts, src/lib/WebsocketClient/client.ts, src/lib/WebsocketClient/types.ts
Adds ability to approve of a song that's currently playing.
=> Pump it up

package-lock.json, package.json, src/App.tsx, src/QuickAdd/QuickAdd.tsx, src/QuickAdd/Results.tsx, src/QuickAdd/ResultsContextProvider.tsx, src/QuickAdd/Search.tsx
- adds [Toast](https://github.com/jossmac/react-toast-notifications) for app notifications
- adds Toast message when songs are added from quick search
- toggles icon when song is added from a users library
- adds `now playing` affordance 
- adds a buttons to let users clear search results / close quick search
- allows users to click off the screen to close quick search
=> Quick add updates

src/QuickAdd/Results.tsx
=> sean is shameful

src/Invitation/ExistingUserInvitation.tsx, src/Invitation/Invitation.tsx, src/Invitation/NewUserInvitation.tsx, src/Invitation/graphql.ts, src/Invitation/index.ts, src/components/SideNav.tsx
Updates invitation flow to be less terrible and to be aware of whether the user has an account already.
New (ignore error, it pops up if password is too short)
Existing
=> Better invitations

src/Player/PlayerPrimitive.tsx
Allow point events so that folks can interact with the video on mobile.
=> Allow folks to poke the video

src/Room/Chat.tsx, src/Room/Main.tsx, src/Room/Messages.tsx, src/Room/MessagesContextProvider.tsx, src/Room/Room.tsx, src/RoomHistory/RoomHistory.tsx, src/RoomHistory/graphql.ts, src/RoomHistory/index.ts
Adds the first version of "room history" to show what all's been played in the past.  Also moves "pinned" messages over by chat, since they're sort of the same deal.
=> Room history

src/RoomHistory/RoomHistory.tsx, src/RoomHistory/graphql.ts
Restrict historical record retrieval to past two days (similar to message history)
=> Restrict room history to past two days only

src/RoomHistory/RoomHistory.tsx, src/RoomHistory/graphql.ts
Allows a song to be added from the room history view.  Link only appears when someone else has played the song.
=> Allow songs to be added from room history

src/SideNav/SideNav.tsx, src/SideNav/Teams.tsx
What do we think about establishing "music" or "your music" — something like that? Where we start with Library but maybe it includes "playlists" if we ever decide to make those exist, tags or genres...IDK what do we think?
=> Riffing on the nav again

src/Library/Songs/Results.tsx, src/Library/graphql.ts, src/QuickAdd/Results.tsx, src/QuickAdd/graphql.ts, src/Room/Message.tsx, src/Room/graphql.ts, src/RoomHistory/RoomHistory.tsx, src/RoomHistory/graphql.ts, src/RoomPlaylist/RoomPlaylist.tsx, src/RoomPlaylist/graphql.ts, src/UserPlaylist/UserPlaylist.tsx, src/UserPlaylist/UserPlaylistRecord.tsx, src/UserPlaylist/graphql.ts, src/components/MediaObject.tsx, src/components/index.ts, src/lib/WebsocketClient/types.ts, src/lib/formatters.ts
I don't know what this looks like, it's mostly a DAN SURPRISE.  I'm just the PR button pusher.
=> Song meta etc

src/Room/Chat.tsx, src/Room/Message.tsx, src/Room/Messages.tsx, src/Room/PinnedMessages.tsx, src/Room/PinnedMessagesContextProvider.tsx, src/Room/Room.tsx, src/lib/WebsocketClient/client.ts, src/lib/WebsocketClient/types.ts
Allows pinned messages to propagate in REAAAAAAL TIIIIIIIIME.
=> Pinned messages xtreeeeeem

src/Invitation/ExistingUserInvitation.tsx, src/Invitation/Invitation.tsx, src/Invitation/NewUserInvitation.tsx, src/Login.tsx, src/PasswordReset.tsx, src/Router/Authorized.tsx, src/Router/Unauthorized.tsx, src/SideNav/SideNav.tsx, src/SideNav/Teams.tsx, src/Signup/Signup.tsx, src/UserSettings/PasswordUpdate.tsx, src/UserSettings/UserSettings.tsx, src/UserSettings/UserUpdate.tsx, src/UserSettings/graphql.ts, src/UserSettings/index.ts, src/lib/useQueryParams.ts
Allows folks to reset their password and to update their password and to update their name!
Also ignore that "settings" is at the top of the nav because I moved it after making the gif.
=> Password reset and things

src/Library/Songs/Results.tsx, src/QuickAdd/Results.tsx
Getting an early start on my bday work day, by fixing my mistake from last night!
I added an imageSize prop to the media object component but didn't pass a size to the media object on results so the height and width were 0.
=> [fixup] Adds images back to quick add search results

src/Player/Player.tsx, src/Player/Volume.tsx, src/Room/Chat.tsx, src/Room/Main.tsx, src/Room/Room.tsx, src/Router/Authorized.tsx, src/SideNav/SideNav.tsx
- clicking the volume icon now supports muting 
- removes some unnecessary markup
=> Birthday workday

src/Library/SongDetails.tsx, src/Library/graphql.ts, src/Recommendations/Recommendations.tsx, src/Recommendations/graphql.ts, src/Recommendations/index.ts, src/Router/Authorized.tsx, src/SideNav/SideNav.tsx
Paired with @trumanshuck on a first attempt at supporting recommendations. This allows a user to recommend a song to one of their team members from within the song details panel in the library. 
It also adds a recommendations page where a user can preview, approve, or reject the recommendation.
=> [feat] Recommendations

src/Library/SongDetails.tsx, src/Library/Songs/Results.tsx, src/Library/Songs/index.tsx, src/Recommendations/Recommendations.tsx, src/components/Th.tsx, src/theme.ts
Cleans up the song details a bit. You can now click view from the table and the details pop out and display relevant information a little better.
Also, adds some text when there are no song recommendations.
=> [feat] Song Details Cleanup

src/Library/SongDetails/Recommendations.tsx, src/Library/SongDetails/SongDetails.tsx, src/Library/SongDetails/graphql.ts, src/Library/SongDetails/index.ts, src/Library/graphql.ts
Allows your own recommendations to be displayed.  Sorry no pix.
=> Recommendererd

.env.template, package-lock.json, package.json, src/Context/WebsocketContextProvider.tsx, src/lib/WebsocketClient/client.ts, src/lib/constants.ts
Hopefully this ends silent websocket drops.  We:
- Have moved all of websocket connect/disconnect to inside of our `Client`
- Set a timeout to disconnect/reconnect if we miss pings for > 10 seconds (we get a ping every 3 seconds by default)
- Reload pretty much the whole app upon reconnecting, which should fetch any missed messages, etc.
- Have added Airbrake and will issue an error upon reconnecting if Airbrake has been configured correctly.
=> Websocket monitor

src/Library/Songs/Results.tsx, src/Library/graphql.ts
Work from Tuesday to allow the library view to display the date that a song was added as well as the source.
=> Add source to library

src/JumpMenu/Menus/Home.tsx, src/JumpMenu/Menus/KeyboardShortcuts.tsx, src/JumpMenu/Results/Results.tsx, src/Player/Volume.tsx, src/Player/VolumeContextProvider.tsx, src/Room/Keyboard/Keyboard.tsx, src/lib/array.ts
Fixes issue where typing regex special characters in jumpbox would cause the app to explode.  Fixes issue where hitting "k" to open keyboard shortcut help would also approve the current song.
Also adds shortcuts:
- `m` to toggle mute/unmute of the player
- `Q` to shuffle-enqueue all selected songs
=> More shortcuts

src/Room/ChatDetails.tsx, src/components/AppHeader.tsx
=> fixes hardcoded gravatar in header

src/Room/Messages.tsx
@trumanshuck 
fixes weird height bug
=> layout-updates
